=== BambusControl/obsidian-unicode-search/resources/save-data-schema.json
{
    "$id": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "BlockFilter": {
            "allOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CodePointInterval"
                },
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/InclusionFlag"
                }
            ],
            "description": "Block of Unicode CodePoints"
        },
        "CategoryFilter": {
            "description": "Filter for a single category.",
            "properties": {
                "abbreviation": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CharacterCategoryType",
                    "description": "Two-letter abbreviation of the category."
                },
                "included": {
                    "description": "Indicates whether a character is included in search or not",
                    "type": "boolean"
                }
            },
            "required": [
                "abbreviation",
                "included"
            ],
            "type": "object"
        },
        "CategoryGroupFilter": {
            "description": "Filters for a group of categories.",
            "properties": {
                "abbreviation": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CharacterCategoryGroupType",
                    "description": "Single letter abbreviation of the category group."
                },
                "categories": {
                    "description": "Categories which belong to the group.",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CategoryFilter"
                    },
                    "type": "array"
                }
            },
            "required": [
                "abbreviation",
                "categories"
            ],
            "type": "object"
        },
        "Character": {
            "allOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CodePointKey"
                },
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CodePointAttribute"
                }
            ],
            "description": "Unicode character representation throughout the plugin"
        },
        "CharacterCategoryGroupType": {
            "enum": [
                "C",
                "L",
                "M",
                "N",
                "P",
                "S",
                "Z"
            ],
            "type": "string"
        },
        "CharacterCategoryType": {
            "enum": [
                "Cc",
                "Cf",
                "Cn",
                "Co",
                "Cs",
                "Ll",
                "Lm",
                "Lo",
                "Lt",
                "Lu",
                "Mc",
                "Me",
                "Mn",
                "Nd",
                "Nl",
                "No",
                "Pc",
                "Pd",
                "Pe",
                "Pf",
                "Pi",
                "Po",
                "Ps",
                "Sc",
                "Sk",
                "Sm",
                "So",
                "Zl",
                "Zp",
                "Zs"
            ],
            "type": "string"
        },
        "CharacterChunk": {
            "description": "Downloaded Unicode Character Database",
            "properties": {
                "codePoints": {
                    "description": "CodePoints downloaded from the Unicode Character Database",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/Character"
                    },
                    "type": "array"
                },
                "initialized": {
                    "type": "boolean"
                },
                "version": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/SaveDataVersion"
                }
            },
            "required": [
                "codePoints",
                "initialized",
                "version"
            ],
            "type": "object"
        },
        "CodePointAttribute": {
            "description": "General attributes of a Unicode code point",
            "properties": {
                "category": {
                    "description": "Unicode General Category abbreviation",
                    "type": "string"
                },
                "glyph": {
                    "description": "The JavaScript string representation, NFC-normalised",
                    "minLength": 1,
                    "type": "string"
                },
                "name": {
                    "description": "Unicode name of the character",
                    "type": "string"
                }
            },
            "required": [
                "category",
                "glyph",
                "name"
            ],
            "type": "object"
        },
        "CodePointInterval": {
            "description": "Represents a closed interval/range of Unicode Code Points",
            "properties": {
                "end": {
                    "type": "number"
                },
                "start": {
                    "type": "number"
                }
            },
            "required": [
                "end",
                "start"
            ],
            "type": "object"
        },
        "CodePointKey": {
            "description": "Universally used key for a Unicode code point",
            "properties": {
                "id": {
                    "description": "The numeric address in the Unicode code space",
                    "type": "number"
                }
            },
            "required": [
                "id"
            ],
            "type": "object"
        },
        "Favorite": {
            "description": "Raw favorite information, as stored in save data",
            "properties": {
                "added": {
                    "description": "Date when the codePoint was added to favorites",
                    "type": "string"
                },
                "quickInsertEnabled": {
                    "description": "Whether the codePoint has a quickInsertEnabled command",
                    "type": "boolean"
                }
            },
            "required": [
                "added",
                "quickInsertEnabled"
            ],
            "type": "object"
        },
        "FavoriteChunk": {
            "description": "Users favorite codePoints",
            "properties": {
                "codePoints": {
                    "description": "List of favorite codePoints",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/RawCodePointFavorite"
                    },
                    "type": "array"
                },
                "initialized": {
                    "type": "boolean"
                },
                "version": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/SaveDataVersion"
                }
            },
            "required": [
                "codePoints",
                "initialized",
                "version"
            ],
            "type": "object"
        },
        "InclusionFlag": {
            "description": "A flag indicating whether a character is included in search or not",
            "properties": {
                "included": {
                    "description": "Indicates whether a character is included in search or not",
                    "type": "boolean"
                }
            },
            "required": [
                "included"
            ],
            "type": "object"
        },
        "MetaChunk": {
            "description": "Meta information for the datastore",
            "properties": {
                "events": {
                    "description": "A collection of unique data events.",
                    "items": {
                        "const": "download_characters",
                        "type": "string"
                    },
                    "type": "array"
                },
                "initialized": {
                    "type": "boolean"
                },
                "pluginVersion": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/PluginVersion",
                    "description": "Latest used version of the plugin which used this data"
                },
                "version": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/SaveDataVersion"
                }
            },
            "required": [
                "events",
                "initialized",
                "pluginVersion",
                "version"
            ],
            "type": "object"
        },
        "PlaneFilter": {
            "description": "Unicode Plane of Unicode Blocks",
            "properties": {
                "blocks": {
                    "description": "Filter criteria for blocks of Unicode characters",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/BlockFilter"
                    },
                    "type": "array"
                },
                "end": {
                    "type": "number"
                },
                "start": {
                    "type": "number"
                }
            },
            "required": [
                "blocks",
                "end",
                "start"
            ],
            "type": "object"
        },
        "PluginVersion": {
            "description": "Version of the plugin.\n\nMust comply with RegEx:\n```^[0-9]+\\\\.[0-9]+\\\\.[0-9]+(?:-[A-Z]+)?$```",
            "enum": [
                "0.2.0",
                "0.2.1",
                "0.2.2",
                "0.2.3",
                "0.3.0",
                "0.4.0",
                "0.4.1",
                "0.5.0",
                "0.6.0",
                "0.6.1",
                "0.7.0",
                "0.7.1",
                "0.7.2",
                "0.7.3",
                "0.7.4"
            ],
            "type": "string"
        },
        "PoolChunk": {
            "description": "User saved character filters",
            "properties": {
                "initialized": {
                    "type": "boolean"
                },
                "unicode": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/UnicodeFilter",
                    "description": "Filter criteria for Unicode characters"
                },
                "version": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/SaveDataVersion"
                }
            },
            "required": [
                "initialized",
                "unicode",
                "version"
            ],
            "type": "object"
        },
        "RawCodePointFavorite": {
            "allOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CodePointKey"
                },
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/Favorite"
                }
            ],
            "description": "Favorite information of a specific codePoint as stored in save data"
        },
        "RawCodePointUse": {
            "allOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CodePointKey"
                },
                {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/RawUseRecord"
                }
            ],
            "description": "Usage information of a specific codePoint as stored in save data"
        },
        "RawUseRecord": {
            "description": "Raw usage information, as stored in save data",
            "properties": {
                "firstUse": {
                    "description": "Alias to hint that a string is a date string",
                    "type": "string"
                },
                "lastUse": {
                    "description": "Alias to hint that a string is a date string",
                    "type": "string"
                },
                "timesUsed": {
                    "type": "number"
                }
            },
            "required": [
                "firstUse",
                "lastUse",
                "timesUsed"
            ],
            "type": "object"
        },
        "SaveDataVersion": {
            "description": "Version of the save data schema.\n\nMust comply with RegEx:\n```^[0-9]+\\\\.[0-9]+\\\\.[0-9]+(?:-[A-Z]+)?$```\n\nThe version of the save data schema is independent of the plugin version",
            "enum": [
                "0.4.0",
                "0.5.0",
                "0.6.0",
                "0.7.0"
            ],
            "type": "string"
        },
        "UnicodeFilter": {
            "description": "User set filter data for Unicode characters.",
            "properties": {
                "categoryGroups": {
                    "description": "Filter criteria for category groups of Unicode characters",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CategoryGroupFilter"
                    },
                    "type": "array"
                },
                "planes": {
                    "description": "Filter criteria for planes of Unicode characters",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/PlaneFilter"
                    },
                    "type": "array"
                }
            },
            "required": [
                "categoryGroups",
                "planes"
            ],
            "type": "object"
        },
        "UseHistoryChunk": {
            "description": "User generated usage data",
            "properties": {
                "codePoints": {
                    "description": "Statistics of the individual codePoint usage",
                    "items": {
                        "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/RawCodePointUse"
                    },
                    "type": "array"
                },
                "initialized": {
                    "type": "boolean"
                },
                "version": {
                    "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/SaveDataVersion"
                }
            },
            "required": [
                "codePoints",
                "initialized",
                "version"
            ],
            "type": "object"
        }
    },
    "description": "Structure of `data.json`, where each fragment is a self-managed data fragment",
    "properties": {
        "characters": {
            "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/CharacterChunk",
            "description": "Local character database"
        },
        "favorites": {
            "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/FavoriteChunk",
            "description": "Favorites saved manually by the user"
        },
        "meta": {
            "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/MetaChunk",
            "description": "Metadata information about the save data itself"
        },
        "pool": {
            "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/PoolChunk",
            "description": "User's character pool configuration"
        },
        "useHistory": {
            "$ref": "https://raw.githubusercontent.com/BambusControl/obsidian-unicode-search/0.7.4/resources/save-data-schema.json#/definitions/UseHistoryChunk",
            "description": "User insertion history"
        }
    },
    "required": [
        "characters",
        "favorites",
        "meta",
        "pool",
        "useHistory"
    ],
    "type": "object"
}

=== BambusControl/obsidian-unicode-search/resources/save-data-examples-real-world/0.7.0.json
{
  "meta": {
    "initialized": true,
    "version": "0.7.0",
    "pluginVersion": "0.7.4",
    "events": []
  },
  "pool": {
    "initialized": true,
    "version": "0.7.0",
    "unicode": {
      "planes": [
        {
          "start": 0,
          "end": 65535,
          "blocks": [
            {
              "start": 0,
              "end": 127,
              "included": true
            },
            {
              "start": 128,
              "end": 255,
              "included": true
            },
            {
              "start": 256,
              "end": 383,
              "included": true
            },
            {
              "start": 384,
              "end": 591,
              "included": true
            },
            {
              "start": 592,
              "end": 687,
              "included": true
            },
            {
              "start": 688,
              "end": 767,
              "included": true
            },
            {
              "start": 768,
              "end": 879,
              "included": true
            },
            {
              "start": 880,
              "end": 1023,
              "included": true
            },
            {
              "start": 1024,
              "end": 1279,
              "included": true
            },
            {
              "start": 1280,
              "end": 1327,
              "included": true
            },
            {
              "start": 1328,
              "end": 1423,
              "included": true
            },
            {
              "start": 1424,
              "end": 1535,
              "included": true
            },
            {
              "start": 1536,
              "end": 1791,
              "included": true
            },
            {
              "start": 1792,
              "end": 1871,
              "included": true
            },
            {
              "start": 1872,
              "end": 1919,
              "included": true
            },
            {
              "start": 1920,
              "end": 1983,
              "included": true
            },
            {
              "start": 1984,
              "end": 2047,
              "included": true
            },
            {
              "start": 2048,
              "end": 2111,
              "included": true
            },
            {
              "start": 2112,
              "end": 2143,
              "included": true
            },
            {
              "start": 2144,
              "end": 2159,
              "included": true
            },
            {
              "start": 2160,
              "end": 2207,
              "included": true
            },
            {
              "start": 2208,
              "end": 2303,
              "included": true
            },
            {
              "start": 2304,
              "end": 2431,
              "included": true
            },
            {
              "start": 2432,
              "end": 2559,
              "included": true
            },
            {
              "start": 2560,
              "end": 2687,
              "included": true
            },
            {
              "start": 2688,
              "end": 2815,
              "included": true
            },
            {
              "start": 2816,
              "end": 2943,
              "included": true
            },
            {
              "start": 2944,
              "end": 3071,
              "included": true
            },
            {
              "start": 3072,
              "end": 3199,
              "included": true
            },
            {
              "start": 3200,
              "end": 3327,
              "included": true
            },
            {
              "start": 3328,
              "end": 3455,
              "included": true
            },
            {
              "start": 3456,
              "end": 3583,
              "included": true
            },
            {
              "start": 3584,
              "end": 3711,
              "included": true
            },
            {
              "start": 3712,
              "end": 3839,
              "included": true
            },
            {
              "start": 3840,
              "end": 4095,
              "included": true
            },
            {
              "start": 4096,
              "end": 4255,
              "included": true
            },
            {
              "start": 4256,
              "end": 4351,
              "included": true
            },
            {
              "start": 4352,
              "end": 4607,
              "included": true
            },
            {
              "start": 4608,
              "end": 4991,
              "included": true
            },
            {
              "start": 4992,
              "end": 5023,
              "included": true
            },
            {
              "start": 5024,
              "end": 5119,
              "included": true
            },
            {
              "start": 5120,
              "end": 5759,
              "included": true
            },
            {
              "start": 5760,
              "end": 5791,
              "included": true
            },
            {
              "start": 5792,
              "end": 5887,
              "included": true
            },
            {
              "start": 5888,
              "end": 5919,
              "included": true
            },
            {
              "start": 5920,
              "end": 5951,
              "included": true
            },
            {
              "start": 5952,
              "end": 5983,
              "included": true
            },
            {
              "start": 5984,
              "end": 6015,
              "included": true
            },
            {
              "start": 6016,
              "end": 6143,
              "included": true
            },
            {
              "start": 6144,
              "end": 6319,
              "included": true
            },
            {
              "start": 6320,
              "end": 6399,
              "included": true
            },
            {
              "start": 6400,
              "end": 6479,
              "included": true
            },
            {
              "start": 6480,
              "end": 6527,
              "included": true
            },
            {
              "start": 6528,
              "end": 6623,
              "included": true
            },
            {
              "start": 6624,
              "end": 6655,
              "included": true
            },
            {
              "start": 6656,
              "end": 6687,
              "included": true
            },
            {
              "start": 6688,
              "end": 6831,
              "included": true
            },
            {
              "start": 6832,
              "end": 6911,
              "included": true
            },
            {
              "start": 6912,
              "end": 7039,
              "included": true
            },
            {
              "start": 7040,
              "end": 7103,
              "included": true
            },
            {
              "start": 7104,
              "end": 7167,
              "included": true
            },
            {
              "start": 7168,
              "end": 7247,
              "included": true
            },
            {
              "start": 7248,
              "end": 7295,
              "included": true
            },
            {
              "start": 7296,
              "end": 7311,
              "included": true
            },
            {
              "start": 7312,
              "end": 7359,
              "included": true
            },
            {
              "start": 7360,
              "end": 7375,
              "included": true
            },
            {
              "start": 7376,
              "end": 7423,
              "included": true
            },
            {
              "start": 7424,
              "end": 7551,
              "included": true
            },
            {
              "start": 7552,
              "end": 7615,
              "included": true
            },
            {
              "start": 7616,
              "end": 7679,
              "included": true
            },
            {
              "start": 7680,
              "end": 7935,
              "included": true
            },
            {
              "start": 7936,
              "end": 8191,
              "included": true
            },
            {
              "start": 8192,
              "end": 8303,
              "included": true
            },
            {
              "start": 8304,
              "end": 8351,
              "included": true
            },
            {
              "start": 8352,
              "end": 8399,
              "included": true
            },
            {
              "start": 8400,
              "end": 8447,
              "included": true
            },
            {
              "start": 8448,
              "end": 8527,
              "included": true
            },
            {
              "start": 8528,
              "end": 8591,
              "included": true
            },
            {
              "start": 8592,
              "end": 8703,
              "included": true
            },
            {
              "start": 8704,
              "end": 8959,
              "included": true
            },
            {
              "start": 8960,
              "end": 9215,
              "included": true
            },
            {
              "start": 9216,
              "end": 9279,
              "included": true
            },
            {
              "start": 9280,
              "end": 9311,
              "included": true
            },
            {
              "start": 9312,
              "end": 9471,
